[project]
name = "wow-character-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psycopg[binary]>=3.2.3",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.36",
    "streamlit>=1.40.2",
    "tqdm>=4.67.1",
]
